includes:
  - base.yaml
atta:
  name: Badge
  episodic: False
  batch_size: 100
  budgets: 400
  Badge:
    steps: 1
    pre: 1
    lr: 1e-6
    d_margin: 0.5
    al_rate: 1e-2
    fisher_alpha: 2000.0
num_workers: 4
log_file: Badge


